apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop.fullname" . }}
  labels:
    {{- include "shop.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  CURRENCY: {{ .Values.config.currency | quote }}
  NEW_CHECKOUT: {{ .Values.config.featureFlags.newCheckout | quote }}
