apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app.kubernetes.io/name: shop
spec:
  selector:
    app.kubernetes.io/name: shop
  ports:
    - name: http
      port: 80
      targetPort: http
